In [4]:
import numpy as np

a = np.random.rand(10)
print(a, '\n')
b = np.random.rand(2, 3)
print(b, '\n')
c = np.random.rand(3, 4, 5)
print(c)

[0.18718747 0.31972962 0.13798728 0.39652325 0.85458092 0.47838874
 0.76982593 0.25915306 0.12747845 0.630357  ] 

[[0.67440376 0.82809938 0.1839654 ]
 [0.03649641 0.67966353 0.70702128]] 

[[[0.27888763 0.68762376 0.6545227  0.90504434 0.7383762 ]
  [0.90206599 0.44699241 0.39253508 0.16849447 0.35796981]
  [0.97884315 0.1807191  0.87704458 0.06647439 0.84590847]
  [0.36786788 0.75816472 0.10501309 0.96530512 0.22836116]]

 [[0.6148984  0.95756732 0.74450221 0.71503068 0.63321269]
  [0.86872012 0.93637832 0.2956578  0.43643265 0.23135256]
  [0.35941963 0.9584336  0.07859803 0.84285557 0.99866347]
  [0.7215616  0.70129049 0.11919778 0.7001228  0.31803179]]

 [[0.0702606  0.71455792 0.09403858 0.88663507 0.1758198 ]
  [0.40634606 0.19490975 0.53482689 0.79983316 0.59779149]
  [0.27649687 0.30777355 0.90446867 0.01719084 0.82007732]
  [0.98055838 0.55249946 0.27813118 0.15790935 0.24858481]]]


In [11]:
import numpy as np

a = np.empty(3)
print(a, '\n')
b = np.empty((3, 4))
print(b, '\n')

arr1 = np.full((3, 4), 15)
print(arr1)

[ 3.17095864e+180  1.02257333e-311 -0.00000000e+000] 

[[2.5e-323 2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323 2.5e-323]] 

[[15 15 15 15]
 [15 15 15 15]
 [15 15 15 15]]


In [18]:
import numpy as np

a = np.array([[1, 2, 3, 4 ,5],
              [6, 7, 8, 9, 10]])
print(a[1, 2])

b = np.array([[[1, 2, 3, 4 ,5],
                [6, 7, 8, 9, 10]],
            [[11, 12, 13, 14 ,15],
                [16, 17, 18, 19, 20]]])
print(b[1, 1, 3])
print(b[1, 1, -1])

8
19
20


In [25]:
import numpy as np

a = np.array([1, 2, 3, 4 ,5, 6, 7, 8, 9, 10])
print(a[1:4:2], '\n')

b = np.array([[1, 2, 3, 4 ,5],
                [6, 7, 8, 9, 10]])
print(b[0:2, 1:3])

[2 4] 

[[2 3]
 [7 8]]


In [28]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

x = a.view()
y = a.copy()

a[0] = 50
print(a, '\n')

print(x)
print(y)

[50  2  3  4  5] 

[50  2  3  4  5]
[1 2 3 4 5]


In [29]:
import numpy as np

a = np.array([1, 2, 3, 4], ndmin= 5)

print(a)

[[[[[1 2 3 4]]]]]


In [32]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.reshape(-1))

[1 2 3 4 5 6]


In [33]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for row in a:
    for e in row:
        print(e)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for row in a:
    for e in row:
        print(e)

In [34]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[11, 12], [13, 14]])
x = a.dot(b)
print(x)

[[37 40]
 [85 92]]
