In [8]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", a, type(a), a.dtype)

a = np.array([[1, 2, 3, 4, 5], [11, 12, 13, 14, 15]])
print("\n2D Array:\n", a, type(a), a.dtype)

1D Array:
 [1 2 3 4 5] <class 'numpy.ndarray'> int64

2D Array:
 [[ 1  2  3  4  5]
 [11 12 13 14 15]] <class 'numpy.ndarray'> int64


In [ ]:
import numpy as np

a = np.array([
    1, 2, 3, 4, 5
], dtype= 'S')
print(a, type(a), a.dtype)

[b'1' b'2' b'3' b'4' b'5'] <class 'numpy.ndarray'> |S1


In [16]:
import numpy as np

a = np.zeros(7)
print(a, '\n')
a = np.ones((7, 2, 3))
print(a)

[0. 0. 0. 0. 0. 0. 0.] 

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [17]:
import numpy as np

a = np.ones((7, 2), order= 'F')
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
import numpy as np

arr1 = np.linspace(0, 5, num= 10)
print(arr1)
arr2 = np.linspace(0, 5, num= 10, endpoint= False)
print(arr2)
arr3 = np.linspace(0, 5, num= 10, retstep= True)
print(arr3)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
(array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]), np.float64(0.5555555555555556))
