In [3]:
import numpy as np

a = np.arange(9)
res = np.split(a, 3)
print(res)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [5]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

res = np.append(a, [[7, 8, 9], [10, 11, 12]], axis= 1)
print(res)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [10]:
import numpy as np

arr = np.array([
    [[123, 4, 5], [2, 3, 4]],
    [[123, 4, 5], [2, 3, 4]]
], dtype= np.int16)
print(arr.itemsize)

2


In [11]:
import numpy as np

a = np.array([11, 12, 13])
b = np.array([22, 33, 44])
print(a % b)

[11 12 13]


In [13]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
print(a % b)
print(a + b)

[[1 2 3]
 [4 5 6]]
[[ 8 10 12]
 [14 16 18]]


In [16]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
res = np.sum(a, axis= 1)
print(a)
print(res)

[[1 2 3]
 [4 5 6]]
[ 6 15]


In [21]:
import numpy as np

a = np.array([3.4j, 2.8j, 6., 1+3j])
print(np.imag(a))
print(np.real(a))
print(np.conj(a))
print(np.angle(a))
print(np.angle(a, deg= True))

[3.4 2.8 0.  3. ]
[0. 0. 6. 1.]
[0.-3.4j 0.-2.8j 6.-0.j  1.-3.j ]
[1.57079633 1.57079633 0.         1.24904577]
[90.         90.          0.         71.56505118]


In [6]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [11, 22, 33, 44, 55]])
print(a, '\n')
a[[0, 1, 2], :] = a[[2, 0, 1], :]
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 22 33 44 55]] 

[[11 22 33 44 55]
 [ 1  2  3  4  5]
 [ 6  7  8  9  0]]


In [15]:
import numpy as np

a = np.array([
    [[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [11, 22, 33, 44, 55]],
    [[23, 24, 25, 26, 27], [36, 37, 38, 39, 30], [114, 224, 334, 444, 554]],
    [[73, 74, 75, 76, 77], [86, 87, 88, 89, 80], [414, 424, 434, 444, 454]]
])
print(a, '\n\n')

#a[[0, 2], :, :] = a[[2, 0], :, :]
a[[0, 2], :, [2, 3]] = a[[2, 0], :, [3, 2]]
print(a)

[[[  1   2   3   4   5]
  [  6   7   8   9   0]
  [ 11  22  33  44  55]]

 [[ 23  24  25  26  27]
  [ 36  37  38  39  30]
  [114 224 334 444 554]]

 [[ 73  74  75  76  77]
  [ 86  87  88  89  80]
  [414 424 434 444 454]]] 


[[[  1   2  76   4   5]
  [  6   7  89   9   0]
  [ 11  22 444  44  55]]

 [[ 23  24  25  26  27]
  [ 36  37  38  39  30]
  [114 224 334 444 554]]

 [[ 73  74  75   3  77]
  [ 86  87  88   8  80]
  [414 424 434  33 454]]]


In [16]:
import numpy as np

arr = np.array([1, 2, np.nan, 4, np.nan])
res = np.isnan(arr)
print(res)

[False False  True False  True]


In [26]:
import numpy as np

arr = np.array([1, 2, np.nan, 4, np.nan])

res = np.isnan(arr)
print(res)

arr2 = arr[~np.isnan(arr)]
print(arr2)

arr3 = np.nan_to_num(arr, nan= 1)
print(arr3)

[False False  True False  True]
[1. 2. 4.]
[1. 2. 1. 4. 1.]


In [27]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [11, 22, 33, 44, 55]])
np.save("data.npy", arr)
res = np.load("data.npy")
print(res)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 22 33 44 55]]


In [28]:
with open('data.txt', 'w') as f:
    f.write("1.0 2.0 3.0\n4.0 5.0 6.0\n7.0 8.0 9.0")

data = np.loadtxt("data.txt")
print(data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [29]:
with open('dataa.csv', 'w') as f:
    f.write("1.0 2.0 3.0\n4.0 5.0 6.0\n7.0 8.0 9.0")

data = np.genfromtxt('dataa.csv', delimiter= ',')
print(data)

[nan nan nan]


In [31]:
# -3x + 2y = 5, x - 2y = 5

arr1 = np.array([[-3, 2], [1, -2]])
arr2 = np.array([5, 5])

res = np.linalg.solve(arr1, arr2)
print(res)

[-5. -5.]


In [32]:
# 4x + 2y = 8, 5x + 3y = 9

arr1 = np.array([[4, 2], [5, 3]])
arr2 = np.array([8, 9])

res = np.linalg.solve(arr1, arr2)
print(res)

[ 3. -2.]
