In [3]:
import numpy as np

a = np.arange(9)
res = np.split(a, 3)
print(res)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [5]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

res = np.append(a, [[7, 8, 9], [10, 11, 12]], axis= 1)
print(res)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [10]:
import numpy as np

arr = np.array([
    [[123, 4, 5], [2, 3, 4]],
    [[123, 4, 5], [2, 3, 4]]
], dtype= np.int16)
print(arr.itemsize)

2


In [11]:
import numpy as np

a = np.array([11, 12, 13])
b = np.array([22, 33, 44])
print(a % b)

[11 12 13]


In [13]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
print(a % b)
print(a + b)

[[1 2 3]
 [4 5 6]]
[[ 8 10 12]
 [14 16 18]]


In [16]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
res = np.sum(a, axis= 1)
print(a)
print(res)

[[1 2 3]
 [4 5 6]]
[ 6 15]


In [21]:
import numpy as np

a = np.array([3.4j, 2.8j, 6., 1+3j])
print(np.imag(a))
print(np.real(a))
print(np.conj(a))
print(np.angle(a))
print(np.angle(a, deg= True))

[3.4 2.8 0.  3. ]
[0. 0. 6. 1.]
[0.-3.4j 0.-2.8j 6.-0.j  1.-3.j ]
[1.57079633 1.57079633 0.         1.24904577]
[90.         90.          0.         71.56505118]
