In [3]:
import numpy as np

arr = np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])

arr = np.nan_to_num(arr, nan=0)
print(arr, '\n')

arr = arr.T
print(arr)

[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]] 

[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [6]:
import numpy as np

arr = np.arange(24).reshape(2, 3, 4)
print(arr.shape)
print(arr, '\n')

new_arr = np.moveaxis(arr, 0, 2)
print(new_arr.shape)
print(new_arr)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

(3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [9]:
import numpy as np

X = np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]
])
print(X, '\n')

col_avg = np.nanmean(X, axis=0)
inds = np.where(np.isnan(X))
X[inds] = np.take(col_avg, inds[1])
print(X)

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]] 

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [7]:
import numpy as np

arr = np.array([10, -5, 20, -8, 15])
arr[arr < 0] = 0
print(arr)

[10  0 20  0 15]
