In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6]])

result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

result = arr.flatten()
print(result)

[1 2 3 4 5 6]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

result = arr[::-1]
print(result)

[5 4 3 2 1]


In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Maximum:", arr.max())
print("Minimum:", arr.min())

print("Rows:", arr.shape[0])
print("Columns:", arr.shape[1])
print("Element at row 1, col 2:", arr[0, 1])

for row in arr:
    for item in row:
        print(item, end=" ")
print()

total = 0
for row in arr:
    for item in row:
        total += item
print("Sum:", total)

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

Maximum: 6
Minimum: 1
Rows: 2
Columns: 3
Element at row 1, col 2: 2
1 2 3 4 5 6 
Sum: 21
[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [7]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Using for loop:")
for i in arr:
    for j in i:
        for k in j:
            print(k)

print("Using nditer:")
for x in np.nditer(arr):
    print(x)

Using for loop:
1
2
3
4
5
6
7
8
Using nditer:
1
2
3
4
5
6
7
8


In [10]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

avg = (arr1 + arr2) / 2
print("Average:\n", avg)

print("Mean:", np.mean(avg))
print("Median:", np.median(avg))
#mode

Average:
 [[3. 4.]
 [5. 6.]]
Mean: 4.5
Median: 4.5
