In [2]:
import numpy as np

In [3]:
arr1d = np.array([1, 2, 3, 4, 5, 6])
print(arr1d, '\n')

arr2d = arr1d.reshape(2, 3)
print(arr2d)

[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, '\n')

print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data Type:", arr.dtype)
print("Item Size:", arr.itemsize)

[[1 2 3]
 [4 5 6]] 

Shape: (2, 3)
Dimension: 2
Data Type: int64
Item Size: 8


In [6]:
arr = np.full((3, 3), 9)
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [7]:
arr = np.linspace(25, 125, 10)
print(arr)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [8]:
python_list = [10, 20, 30, 40, 50]
print(python_list, type(python_list))

numpy_array = np.array(python_list)
print(numpy_array, type(numpy_array))

[10, 20, 30, 40, 50] <class 'list'>
[10 20 30 40 50] <class 'numpy.ndarray'>


In [9]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

reversed_arr = arr[::-1]
print(reversed_arr)

[1 2 3 4 5]
[5 4 3 2 1]


In [11]:
arr = np.arange(1, 49).reshape(4, 4, 3)
print(arr, '\n')

value = arr[1, 0, -1]
print(value)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]] 

15


In [13]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr, '\n')

res = arr[1::2, 0::2]
print(res)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 5  7]
 [13 15]]


In [14]:
arr = np.arange(1, 49).reshape(4, 4, 3)
print(arr, '\n')

sliced = arr[1, :2, :2]
print(sliced)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]] 

[[13 14]
 [16 17]]


In [17]:
arr = np.array([[23, 56, 78, 93], [71, 82, 13, 24]])
print(arr, '\n')

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:
            arr[i][j] = -1

print(arr)

[[23 56 78 93]
 [71 82 13 24]] 

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [20]:
arr = np.array([1, 0, 2, 0, 3, 0, 4])
print(arr)

res = np.nonzero(arr)
print(res[0])

[1 0 2 0 3 0 4]
[0 2 4 6]


In [22]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print(arr1)
print(arr2)

add = arr1 + arr2
print("\nAddition:", add)
multiply = arr1 * arr2
print("Multiplication:", multiply)

[1 2 3 4]
[5 6 7 8]

Addition: [ 6  8 10 12]
Multiplication: [ 5 12 21 32]


In [24]:
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])
print(arr1)
print(arr2)

print(np.dot(arr1, arr2))

[15 20 25]
[10 40 37]
1875
